### ISSUE TITLE
Adapt fonts and themes

### ISSUE THREAD

**Issue by juanvaccarezza** [MarcoIeni/spaceclipse#1]
Hi!
Awesome work, many thanks.

I created a font theme to look like spacemacs:
http://www.eclipsecolorthemes.org/?view=theme&id=60119

I hope you like it.

**Comment by marcoieni** [comment]
Hi, thanks.

Do you want to do a pull request and link the theme in the README?

**Comment by juanvaccarezza** [comment]
Sure!
My pleasure

**Comment by marcoieni** [comment]
Hi @juanvaccarezza 
Do you still want to do the PR?

**Comment by marcoieni** [comment]
closed for inactivity. Anyway, if you want to install the theme it's there :)
